import Tea4  from "../assets/image/Tea4.png";

export const productList = [
  {
    id: 1,
    name: "Tea1",
    type: "Tea",
    price: 25000,
    image: Tea4,
    qty: 1,
    description: "A great Tea",
  },
  {
    id: 2,
    name: "Tea2",
    type: "Tea",
    price: 35000,
    image: "src/assets/image/Tea2.png",
    qty: 1,
    description: "A great Tea",
  },
  {
    id: 3,
    name: "Tea3",
    type: "Tea",
    price: 50000,
    image: "src/assets/image/Tea3.png",
    qty: 1,
    description: "A great Tea",
  },
  {
    id: 4,
    name: "Tea4",
    type: "Tea",
    price: 55000,
    image: "src/assets/image/Tea1.png",
    qty: 1,
    description: "A great Tea",
  },

  {
    id: 5,
    name: "Coffee1",
    type: "Coffee",
    price: 30000,
    image: "src/assets/image/Coffee1.png",
    qty: 1,
    description: "A great Coffee",
  },
  {
    id: 6,
    name: "Coffee2",
    type: "Coffee",
    price: 35000,
    image: "src/assets/image/Coffee2.png",
    qty: 1,
    description: "A great Coffee",
  },
  {
    id: 7,
    name: "Coffee3",
    type: "Coffee",
    price: 40000,
    image: "src/assets/image/Coffee3.png",
    qty: 1,
    description: "A great Coffee",
  },
  {
    id: 8,
    name: "Coffee4",
    type: "Coffee",
    price: 45000,
    image: "src/assets/image/Coffee4.png",
    qty: 1,
    description: "A great Coffee",
  },
  {
    id: 9,
    name: "Juice1",
    type: "Juice",
    price: 55000,
    image: "src/assets/image/Juice1.png",
    qty: 1,
    description: "A great Juice",
  },

  {
    id: 10,
    name: "Juice2",
    type: "Juice",
    price: 55000,
    image: "src/assets/image/Juice2.png",
    qty: 1,
    description: "A great Juice",
  },
  {
    id: 11,
    name: "Juice3",
    type: "Juice",
    price: 55000,
    image: "src/assets/image/Juice3.png",
    qty: 1,
    description: "A great Juice",
  },

  {
    id: 12,
    name: "Juice4",
    type: "Juice",
    price: 55000,
    image: "src/assets/image/Juice4.png",
    qty: 1,
    description: "A great Juice",
  },
  {
    id: 13,
    name: "Bakery1",
    type: "Bakery",
    price: 55000,
    image: "src/assets/image/Bakery1.png",
    qty: 1,
    description: "A great Bread",
  },
  {
    id: 14,
    name: "Bakery2",
    type: "Bakery",
    price: 55000,
    image: "src/assets/image/Bakery2.png",
    qty: 1,
    description: "A great Bread",
  },
  {
    id: 15,
    name: "Dessert1",
    type: "Dessert",
    price: 55000,
    image: "src/assets/image/Dessert1.png",
    qty: 1,
    description: "A great Dessert",
  },
  {
    id: 16,
    name: "Dessert2",
    type: "Dessert",
    price: 55000,
    image: "src/assets/image/Dessert2.png",
    qty: 1,
    description: "A great Dessert",
  },
];
